### ISSUE TITLE
Handle SQL statements inside variables

### ISSUE THREAD

**Issue by godwhoa** [agnivade/sqlargs#11]
Currently something like this gets ignored
```go
q := `INSERT INTO t(c1 c2) VALUES ($1, $2)`
db.Exec(q, p1, p2) // want `Invalid query: syntax error at or near "c2"`
```
Lots of code-bases do it like that so, it's something worth solving.

**Comment by agnivade** [comment]
Yes I know. The problem is that variables are that: variable. I am not sure if it's possible to know the value of a variable in a static code analysis. 

If you just change `q := ` to `const q =`, it works.

It is on my radar, though. I will check if it is possible to get the value of a variable.
