### ISSUE TITLE
Add support for sqlx

### ISSUE THREAD

**Issue by godwhoa** [agnivade/sqlargs#4]
Any plans for adding [sqlx](https://github.com/jmoiron/sqlx) support?

P.S.: Sorry for pestering at such an early stage into development :sweat_smile:.
I would like to contribute if you can guide me.

**Comment by agnivade** [comment]
Seems like a reasonable request. But I can't promise on timelines.

If you want to contribute, you need to modify the `isProperSelExpr` function to accept `sqlx` methods too. And then extract the query and pass it to `analyzeQuery` function. Of course, please add tests too. :)

The code is fairly well commented and small.

**Comment by agnivade** [comment]
Fixed with https://github.com/agnivade/sqlargs/commit/ada05e886112626086cac1604a9a96f93bc68e70.
